"""No example block in README.md is hand-typed.

Each fenced block preceded by `<!-- generated: NAME -->` is regenerated by running
the CLI over a figure this test builds from `corpus.py`, and must appear verbatim in
the real output. Verbatim-and-contiguous rather than equal, so a block may quote the
CLAIM line without also quoting the certificate above it.

RESULTS.md's blocks are `bench.py`'s own stdout and are not covered here: the
benchmark takes a minute and its numbers are machine-specific, so `bench.py` is what
regenerates them, and the run of record is stamped with its own commit and machine.
"""

import io
import os
import re
import contextlib

import pytest

import corpus
from planimeter import cli

README = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                      "README.md")
BLOCK = re.compile(r"<!--\s*generated:\s*(\S+)\s*-->\s*\n```\n(.*?)```", re.S)


def figures(tmp):
    """The three files the README talks about, written from the corpus."""
    seg, truth = corpus.FAMILIES["grid(2)"]
    paths = {}
    corpus.write_svg(os.path.join(tmp, "plan.svg"), seg)
    paths["plan"] = ["plan.svg"]
    loop = dict((n, s) for n, s, _t, _w in corpus.edits(seg, truth))["loop"]
    corpus.write_svg(os.path.join(tmp, "plan_loop.svg"), loop)
    corpus.write_svg(os.path.join(tmp, "wall_missing_the_floor.svg"),
                     corpus.REFUSALS["wall missing the floor"][0])
    paths["wall"] = ["wall_missing_the_floor.svg"]
    paths["check-held"] = ["check", "plan_loop.svg", "--faces", "5"]
    paths["check-broken"] = ["check", "plan.svg", "--faces", "5"]
    return paths


def run(argv, cwd):
    here = os.getcwd()
    os.chdir(cwd)
    try:
        out = io.StringIO()
        with contextlib.redirect_stdout(out):
            cli.main(argv)
        return out.getvalue()
    finally:
        os.chdir(here)


def blocks():
    return BLOCK.findall(open(README, encoding="utf-8").read())


def test_the_readme_has_generated_blocks_to_check():
    assert len(blocks()) == 4, [n for n, _ in blocks()]


@pytest.mark.parametrize("name,body", blocks())
def test_a_readme_block_is_verbatim_cli_output(name, body, tmp_path):
    tmp = str(tmp_path)
    argv = figures(tmp)[name]
    got = run(argv, tmp)
    want = body.rstrip("\n")
    assert want in got.replace("\r\n", "\n"), (
        "README block %r is not what the CLI prints.\n--- README ---\n%s\n"
        "--- actual ---\n%s" % (name, want, got))


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-q"]))
